# Generated by Django 5.0.6 on 2024-07-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at_task_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
